name: 'Algorand Sandbox'
description: 'Setup an Algorand sandbox network'
inputs:
  config:
    description: 'Sandbox config'
    required: false
    default: 'release'
outputs:
  mnemonic:
    description: 'Mnemonic of an account that has some algos in it'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
branding:
  icon: 'box'  
  color: 'white'
