name: 'Algorand Sandbox'
description: 'Setup an Algorand sandbox network'
inputs:
  config:
    description: 'Sandbox config. Is either one of release/beta/dev/nightly, or the contents of a custom config file'
    required: false
    default: 'release'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.config }}
branding:
  icon: 'box'  
  color: 'white'
