on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test sandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup sandbox
        uses: ./ # Uses an action in the root directory