on: [push]

jobs:
  algorand-sandbox-job:
    runs-on: ubuntu-latest
    name: Test sandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup sandbox
        uses: ./ # Uses an action in the root directory
      - name: Test
        run: |
          curl localhost:4001/v2/status -H "X-Algo-API-Token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"